### ISSUE TITLE
[explore] show query in modal while query is running

### ISSUE THREAD

**Issue by ascott** [airbnb/superset#1644]
show query in modal while query is running, currently it's empty. useful for long running queries.

![screenshot 2016-11-18 15 40 37](https://cloud.githubusercontent.com/assets/130878/20450420/4c581c22-ada5-11e6-903b-a9a0d4a327f2.png)

**Comment by vera-liu** [comment]
query is formed in models.py [https://github.com/airbnb/superset/blob/34d0dd9d6e074e41968c39247d66e19fd551c57b/superset/models.py#L1163](url) and returned along with viz object in viz.py [https://github.com/airbnb/superset/blob/34d0dd9d6e074e41968c39247d66e19fd551c57b/superset/viz.py#L170](url). So to get query before the viz returns we may have to create a new endpoint to return query separately, which I don't think would be necessary since this use case is quite rare?

**Comment by vera-liu** [comment]
merged into deprecate_v1
