### ISSUE TITLE
Autocomplete defaults to ALL CAPS instead of lowercase

### ISSUE THREAD

**Issue by jefffeng** [airbnb/superset#1852]
Currently, autocomplete defaults to lowercase letters.  Instead, we should autocomplete using the same case that the text is typed in

<img width="1485" alt="screen shot 2016-12-15 at 11 46 39 pm" src="https://cloud.githubusercontent.com/assets/18297825/21255434/c195dd0e-c320-11e6-8d9f-60a9ab81c1cc.png">

**Comment by scherrey** [comment]
Shouldn't autocomplete simply use the case already being used by the user
rather than force one way or another? I never use upper case for SQL
keywords but I know I'd be frustrated if I did and the tool insisted on
lower case. Don't "fix" the problem by breaking it for other people is my
main concern.

**Comment by jefffeng** [comment]
Good point @scherrey - issue updated

**Comment by vera-liu** [comment]
Looked into this a bit, we either have to change library function like [http://stackoverflow.com/questions/35183311/ace-editor-autocompletion-keywords-in-upper-case](url) or create a customized completer with all words in upper case...which I think might be an overkill for this case.

**Comment by vera-liu** [comment]
https://github.com/airbnb/superset/pull/2316
