### ISSUE TITLE
Why my superset runs so slowly?

### ISSUE THREAD

**Issue by BrooklynWang** [airbnb/superset#1867]
It takes over twenty seconds after clicking a link.  Any methods to speed up?
Many thanks.

version: 0.14.1

**Comment by xrmx** [comment]
The one who knows if your machine / database / network is slow or under stress it's you. I don't think we can help there.

**Comment by data-strategy** [comment]
Yes, it is running very slow, will take more 20s when refresh data. Did you fix that?

**Comment by iandyilove** [comment]
me2.I have installed 2 supersets.version superset-0.17.6.one is in my mac virtualbox.one is in linux vir server.But I got the same problems.When I logged into superset,it took me very long time to show the main page.The second machine even didn't show the page until I stop the service.Anyone know what the problem is .Seems like some network is wrong?

**Comment by iandyilove** [comment]
>I found my problem is ah very very low bit problem.When I started the sup service,I tapped ctrl + Z,and I thought that was the correct way to let the service run in the background.oh..I forgot it.It is hangout.Just parsed the service.I know the fg! But I forgot the bg.Hope U guys won't follow my fault.

**Comment by AnithaMurugesan** [comment]
Yes...I too got this problem.
I am working with Superset 0.19.0.  I am using superset as iframe inside my project. The problem is that the superset page is taking more time to load.  Is the problem with Gunicorn webserver? I have changed the worker type of gunicorn from sync to async and tried with eventlet and gevent. Still, it takes more time to load. How can I optimize the speed. Thanks in advance.
