### ISSUE TITLE
Usability Feedback about Query button in Explore screen 

### ISSUE THREAD

**Issue by kkalyan** [airbnb/superset#664]
Many first timers are finding it hard to identify that they need to click on 'Query' to refresh the data after changing some parameters. 

![image](https://cloud.githubusercontent.com/assets/391567/16292397/f2791336-38c5-11e6-8a13-aa34fde3e2e2.png)

May be different color for 'Query' button or Renaming to 'Run Query' would help.

**Comment by apitts** [comment]
I would add a bit to this. It's a little confusing that there are two query buttons - one top left and one top right. It would be simpler to only have one. Also, it may be worth not running the query on chart type change as too frequently the data is not set-up for the new chart type which leads to an error and you cannot fix that error without changing to another chart type. My suggestion would be to move query to the right of the chart type dropdown, make it a bold color and only show one query button. Also, only run query when the user clicks query not on chart type change as we don't re-run automatically when other inputs are changed.

**Comment by dylburger** [comment]
+1. My first intuition is to click the orange query button near the top-right when I want to run my query again, but it displays the SQL query. For most users, I'd imagine the ideal action is to "run query", not "show query". As others have noted above, perhaps changing the language on one (or both) buttons would be ideal.

**Comment by ascott** [comment]
the query button and action buttons along the top have been redesigned and are more clear now. i think we could still add some better ux around when a user needs to click the query button, but going to close this for now since the main issue is resolved.

<img width="1437" alt="screenshot 2017-01-31 12 06 52" src="https://cloud.githubusercontent.com/assets/130878/22482457/ef2743d2-e7ad-11e6-873e-6f948cf8c1b7.png">
