### ISSUE TITLE
Boxplot is showing flat lines 

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/superset#905]

**Comment by tshauck** [comment]
Looked into this a bit.  It looks to be caused by fact that the line `df = super(BoxPlotViz, self).get_df(query_obj)` aggregates according to the group by. But this is too early because the rest of the BoxPlotViz get_df tries to calculate the quartiles on a single value.

The quick and dirty solution is to create a dataframe from the raw query, then you're able to produce a boxplot with variation.

**Comment by monkevlar** [comment]
What if I face this exact issue? Has this been fixed? I really can't understand what I'm doing wrong.

**Comment by edwardlxb** [comment]
Still got the same issue. The boxplot is showing flatlines
